### ISSUE TITLE
503 connecting to imdb

### ISSUE THREAD

**Issue by calebcall** [SaulFemm/PlexHolidays#3]
This may be a temporary IMDB issue but I got the following error for all my movies (previous version of the script from 4 days ago worked fine)

```Exception in thread Thread-1906:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "main.py", line 86, in run
    self.imdb_id = self.get_imdb_id()
  File "main.py", line 149, in get_imdb_id
    results = [ _ for _ in self.imdbpie.search_for_title(self.plex_obj.title) if _.get('year') ]
  File "/usr/local/lib/python3.6/site-packages/imdbpie/imdbpie.py", line 148, in search_for_title
    'http://www.imdb.com/xml/find?{0}'.format(query_params)
  File "/usr/local/lib/python3.6/site-packages/imdbpie/imdbpie.py", line 286, in _get
    resp.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://www.imdb.com/xml/find?json=1&nr=1&tt=on&q=Zootopia```

**Comment by SaulFemm** [comment]
This method of getting the IMDb ID is no longer used, thank God!
